<?php
/**
 * This is the main Web application configuration. Any writable
 * CWebApplication properties can be configured here.
 * Generated by AppManager
 *
 * @version 2013-04-03 16:17:23
 */
 
// uncomment the following to define a path alias
// Yii::setPathOfAlias('local','path/to/local-folder');

// This is the main Web application configuration. Any writable
// CWebApplication properties can be configured here.

// Define a path alias for the Bootstrap extension as it's used internally.
// In this example we assume that you unzipped the extension under protected/extensions.
Yii::setPathOfAlias('bootstrap', dirname(__FILE__).'/../extensions/bootstrap');
return array(
    'basePath' => 'E:\\project\\myapp\\source\\protected\\config\\..',
    'name' => 'My App',
    'theme' => 'bootstrap',
    'preload' => array(
        'log',
    ),
    'import' => array(
        'application.models.*',
        'application.components.*',
    ),
    'modules' => array(
        'gii' => array(
            'class' => 'system.gii.GiiModule',
            'password' => '123456',
            'ipFilters' => array(
                '127.0.0.1',
                '::1',
            ),
            'generatorPaths' => array(
                'bootstrap.gii',
            ),
        ),
        'admin',
        'appManager',
    ),
    'components' => array(
        'messages' => array(
            'class' => 'MyPhpMessageSource',
        ),
        'user' => array(
            'allowAutoLogin' => true,
        ),
        'urlManager' => array(
            'urlFormat' => 'path',
            'rules' => array(
                '<controller:\w+>/<id:\d+>' => '<controller>/view',
                '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
                '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
            ),
        ),
        'db' => array(
            'connectionString' => 'mysql:host=localhost;dbname=yii',
            'emulatePrepare' => true,
            'username' => 'root',
            'password' => 'root',
            'charset' => 'utf8',
        ),
        'errorHandler' => array(
            'errorAction' => 'site/error',
        ),
        'log' => array(
            'class' => 'CLogRouter',
            'routes' => array(
                array(
                    'class' => 'CFileLogRoute',
                    'levels' => 'error, warning',
                ),
            ),
        ),
        'bootstrap' => array(
            'class' => 'bootstrap.components.Bootstrap',
        ),
    ),
    'params' => array(
        'adminEmail' => 'xxx',
        'paramName' => 'abcd',
        'salt' => 'P@bl0',
        'someOption' => true,
    ),

	// application-level parameters that can be accessed
	// using Yii::app()->params['paramName']
	'params' => require(dirname(__FILE__).'/params.php'),

        'language' => 'vi', // the language that the user is using and the application should be targeted to        
        


);
